### ISSUE TITLE
Vial-QMK Firmware source code

### ISSUE THREAD

**Issue by kroegerama** [TweetyDaBird/Little-Big-Scroll#2]
This is an interesting project, but where can I find the source code of your hex file?

I can't find the Little-Big-Scroll in [`vial-qmk`](https://github.com/vial-kb/vial-qmk/tree/vial/keyboards/) or in your fork of [`qmk-firmware`](https://github.com/TweetyDaBird/qmk_firmware/tree/tweetydabird/keyboards).

**Comment by TweetyDaBird** [comment]
That’s because I’m lazy and haven’t finished tweaking them yet. I got distracted playing with the prototype for the LittleBigScroll 6 instead. I’ll get around to finish them in a couple of days probably.

**Comment by kroegerama** [comment]
Oh, I can totally relate to that 😄  Thanks for letting me know!

**Comment by lesshonor** [comment]
Any update on this?
I've run into two people who would like to customize (...and troubleshoot) their kits, and most don't have enough experience with QMK (or a multimeter) to reverse-engineer it.

**Comment by TweetyDaBird** [comment]
Well, life keeps interfering unfortunately. I will get to it, I promise.

Side note, what kind of troubleshooting is it you need the firmware for? All the info you would ever need is in the pdf file with the schematic, without any need to reverse engineer anything? It should even give you more info than the firmware could.

**Comment by lesshonor** [comment]
Late, but the disconnect ended up being that the seller of the PCBs used the v1.1 release to get the files made, and that has _wildly_ different pin definitions from "v1.11".
(Would you consider calling this "rev 2" so that distinction is clearer? These are breaking changes. https://semver.org/)

**Comment by TweetyDaBird** [comment]
Well, considering nothing reached beyond pre-releases before v1.11 I think it should be fine as is, although I can understand the confusion. And between 1.1 and 1.11 there is only silkscreen fixes. V1.0 however is vastly different.

**Comment by Brittle73** [comment]
> That’s because I’m lazy and haven’t finished tweaking them yet. I got distracted playing with the prototype for the LittleBigScroll 6 instead. I’ll get around to finish them in a couple of days probably.

Do you have an update?

**Comment by TweetyDaBird** [comment]
LSB 4 & LSB 6 is now in main QMK repo, so should be less confusing.

* Note that using QMK online Configurator still isn't a great idea, since the main feature, ie the encoder won't work in that case.

VIAL firmware is available in my fork, but remains WIP for now.

**Comment by TweetyDaBird** [comment]
VIAL is merged into main Git, source code is available, and pre configured .HEX files are available in this Git
